# Generated by Django 5.0 on 2024-02-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pdf_url',
            field=models.CharField(max_length=255),
        ),
    ]
